#!/usr/bin/python -u

import matplotlib as mpl
from matplotlib import rc
rc('text', usetex=True)
mpl.use('Agg')
import numpy as np
import pylab

from scipy.interpolate import interp1d as interpolate

h = 4E-6


fpp,App = np.loadtxt('inputs/pp_spectrum.txt').T

f_15icm, t_15icm = np.loadtxt('inputs/15icm_thick_IR.txt').T

# f50 = flo_50[flo_50 < 500]
# T50 = Tlo_50[flo_50 < 500]
# f50 = np.append(f50,fhi_50[fhi_50 >= 500])
# T50 = np.append(T50,Thi_50[fhi_50 >= 500])
#
# f100 = flo_100[flo_100 < 500]
# T100 = Tlo_100[flo_100 < 500]
# f100 = np.append(f100,fhi_100[fhi_100 >= 500])
# T100 = np.append(T100,Thi_100[fhi_100 >= 500])

App[App < 0] = 0

A = interpolate(fpp,App,'linear', fill_value="extrapolate")
A_f_15icm = 1-np.exp(-A(f_15icm)*h*100)

header = 'Wavenumber (cm^-1)  T  A'
fmt = '%.6f %.6f %.6f'

np.savetxt('15icm_thick_IR_Cardiff.txt', np.vstack([f_15icm,t_15icm,A_f_15icm]).T, \
           header = header, fmt = fmt)
